name: Lint

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: |
          cd python
          uv sync
          uv install

      - name: Run ruff
        run: |
          cd python
          uv run ruff check
