name: Lint

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install bash
        run: sudo apt-get update && sudo apt-get install -y bash

      - name: Install uv
        run: make install-uv

      - name: Install ruff
        run: make install-ruff

      - name: Verify
        run: make verify
